@CreateWebUserCommand_HostAddress = http://localhost:5176

### Create User Command
POST {{CreateWebUserCommand_HostAddress}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}
